from datetime import datetime, timedelta
from app.repositories.roasting_log_repository import RoastingLogRepository
from app.schemas.roasting import RoastingLogCreate

def test_create_roasting_log(db_session):
    repo = RoastingLogRepository(db_session)
    # Use strict schema for basic create test
    log_in = RoastingLogCreate(
        batch_no="B001",
        target_bean_id=1,
        input_weight_total=10.0,
        output_weight_total=8.5,
        loss_rate=15.0
    )
    log = repo.create(log_in)
    assert log.id is not None
    assert log.batch_no == "B001"
    # roast_date is autogenerated by DB default or None if not set? 
    # Let's assume verifying creation is enough.

def test_get_multi_with_filters(db_session):
    repo = RoastingLogRepository(db_session)
    
    today = datetime.now()
    yesterday = today - timedelta(days=1)
    
    # Use dict to force roast_date setting since Schema might not have it
    repo.create({
        "batch_no": "B00X", "target_bean_id": 1, "roast_date": yesterday,
        "input_weight_total": 10, "output_weight_total": 9
    })
    repo.create({
        "batch_no": "B00Y", "target_bean_id": 1, "roast_date": today,
        "input_weight_total": 10, "output_weight_total": 9
    })
    repo.create({
        "batch_no": "B00Z", "target_bean_id": 2, "roast_date": today,
        "input_weight_total": 10, "output_weight_total": 9
    })

    # Test Date Filter
    logs = repo.get_multi(filters={"start_date": today.date()})
    assert len(logs) == 2 # B00Y, B00Z

    # Test Bean Filter
    logs = repo.get_multi(filters={"bean_id": 2})
    assert len(logs) == 1
    assert logs[0].batch_no == "B00Z"

def test_get_latest_batch_no(db_session):
    repo = RoastingLogRepository(db_session)
    repo.create({
        "batch_no": "BATCH_99", "target_bean_id": 1, "roast_date": datetime.now(),
        "input_weight_total": 10, "output_weight_total": 9
    })
    
    latest = repo.get_latest_batch_no()
    assert latest == "BATCH_99"
