"""Add english_name and grade to beans

Revision ID: 8a659a421166
Revises: f4ad20730592
Create Date: 2025-12-03 21:40:52.218538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8a659a421166'
down_revision: Union[str, None] = 'f4ad20730592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blends_id', table_name='blends')
    op.drop_index('ix_blends_name', table_name='blends')
    op.drop_table('blends')
    op.add_column('beans', sa.Column('english_name', sa.String(length=200), nullable=True, comment='영문 표기 (명세서 기준)'))
    op.add_column('beans', sa.Column('grade', sa.String(length=50), nullable=True, comment='등급 (G1, G2, AA, SHB 등)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beans', 'grade')
    op.drop_column('beans', 'english_name')
    op.create_table('blends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('recipe', sqlite.JSON(), nullable=False),
    sa.Column('target_roast_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blends_name', 'blends', ['name'], unique=False)
    op.create_index('ix_blends_id', 'blends', ['id'], unique=False)
    # ### end Alembic commands ###
