"""Add invoice_number and supplier_name to InboundDocument

Revision ID: f4ad20730592
Revises: faf057890eab
Create Date: 2025-12-03 20:01:46.098969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f4ad20730592'
down_revision: Union[str, None] = 'faf057890eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blends_id', table_name='blends')
    op.drop_index('ix_blends_name', table_name='blends')
    op.drop_table('blends')
    op.add_column('inbound_documents', sa.Column('invoice_number', sa.String(length=100), nullable=True, comment='명세서 고유번호'))
    op.add_column('inbound_documents', sa.Column('supplier_name', sa.String(length=100), nullable=True, comment='공급처명'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_documents', 'supplier_name')
    op.drop_column('inbound_documents', 'invoice_number')
    op.create_table('blends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('recipe', sqlite.JSON(), nullable=False),
    sa.Column('target_roast_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blends_name', 'blends', ['name'], unique=False)
    op.create_index('ix_blends_id', 'blends', ['id'], unique=False)
    # ### end Alembic commands ###
