"""Initial migration

Revision ID: faf057890eab
Revises: 
Create Date: 2025-12-03 18:32:23.924743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf057890eab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True, comment='원두 유형 (GREEN_BEAN, ROASTED_SINGLE, BLEND)'),
    sa.Column('parent_bean_id', sa.Integer(), nullable=True, comment='부모 생두 ID (원두인 경우)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='원두명'),
    sa.Column('origin', sa.String(length=100), nullable=True, comment='원산지'),
    sa.Column('origin_code', sa.String(length=10), nullable=True, comment='국가 코드 (Eth, K, Co 등)'),
    sa.Column('variety', sa.String(length=50), nullable=True, comment='품종 (Arabica, Robusta 등)'),
    sa.Column('processing_method', sa.String(length=50), nullable=True, comment='가공 방식 (Washed, Natural, Honey 등)'),
    sa.Column('purchase_date', sa.Date(), nullable=True, comment='구매일'),
    sa.Column('purchase_price_per_kg', sa.Float(), nullable=True, comment='kg당 구매 가격 (생두)'),
    sa.Column('cost_price', sa.Float(), nullable=True, comment='원가 (생두: 매입가, 원두: 생산원가)'),
    sa.Column('avg_cost_price', sa.Float(), nullable=True, comment='평균 매입/생산 단가'),
    sa.Column('quantity_kg', sa.Float(), nullable=True, comment='재고량 (kg)'),
    sa.Column('roast_level', sa.String(length=20), nullable=True, comment='로스팅 단계 (Light, Medium, Dark)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='메모'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_bean_id'], ['beans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beans_id'), 'beans', ['id'], unique=False)
    op.create_index(op.f('ix_beans_name'), 'beans', ['name'], unique=False)
    op.create_table('inbound_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='파일 경로'),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='업로드 일시'),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'CONFIRMED', name='inboundstatus'), nullable=True, comment='상태'),
    sa.Column('raw_ocr_data', sa.JSON(), nullable=True, comment='OCR 추출 원본 데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_documents_id'), 'inbound_documents', ['id'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INBOUND', 'ROASTING_IN', 'ROASTING_OUT', 'BLENDING_IN', 'BLENDING_OUT', 'SALES', 'LOSS', 'ADJUST', name='transactiontype'), nullable=False, comment='거래 유형'),
    sa.Column('amount_kg', sa.Float(), nullable=False, comment='수량 (+/-)'),
    sa.Column('cost_price', sa.Float(), nullable=True, comment='당시 단가'),
    sa.Column('current_quantity', sa.Float(), nullable=False, comment='변동 후 잔고'),
    sa.Column('related_doc_id', sa.Integer(), nullable=True, comment='관련 문서 ID (입고 시)'),
    sa.Column('reason', sa.Text(), nullable=True, comment='사유'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['related_doc_id'], ['inbound_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_logs_id'), 'inventory_logs', ['id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blend_bean_id', sa.Integer(), nullable=False, comment='블렌드 제품 ID'),
    sa.Column('ingredient_bean_id', sa.Integer(), nullable=False, comment='재료 원두 ID'),
    sa.Column('ratio_percent', sa.Float(), nullable=False, comment='배합 비율 (%)'),
    sa.ForeignKeyConstraint(['blend_bean_id'], ['beans.id'], ),
    sa.ForeignKeyConstraint(['ingredient_bean_id'], ['beans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_inventory_logs_id'), table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index(op.f('ix_inbound_documents_id'), table_name='inbound_documents')
    op.drop_table('inbound_documents')
    op.drop_index(op.f('ix_beans_name'), table_name='beans')
    op.drop_index(op.f('ix_beans_id'), table_name='beans')
    op.drop_table('beans')
    # ### end Alembic commands ###
